### ISSUE TITLE
 Base quick-sqlite module not found. Maybe try rebuilding the app.

### ISSUE THREAD

**Issue by Peter-Maguire** [margelo/react-native-nitro-sqlite#7] opened 2023-06-21 20:23 UTC
Trying to run on android through Expo.  
  
Expo Version 48.0.18
RN: 0.71.8  
  
Full error:
```
Error: Base quick-sqlite module not found. Maybe try rebuilding the app., js engine: hermes
Invariant Violation: "main" has not been registered. This can happen if:
* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called., js engine: hermes


```

**Comment by traildex** [comment] 2023-06-24 05:33
Experiencing this, I was getting the following error on `npx eas build --profile development --platform android`

> FAILURE: Build completed with 2 failures.
> 1: Task failed with an exception.
> -----------
> * Where:
> Build file '/home/expo/workingdir/build/node_modules/react-native-quick-sqlite/android/build.gradle' line: 42
> * What went wrong:
> A problem occurred evaluating project ':react-native-quick-sqlite'.
> > Cannot get property 'hermesEnabled' on extra properties extension as it does not exist
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> A problem occurred configuring project ':react-native-quick-sqlite'.
> > compileSdkVersion is not specified. Please add it to build.gradle
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> ==============================================================================

After much headache, I added `hermesEnabled=true` to the end of the Top-level gradle.properties. Then ran `npx react-native clean-project` followed by `yarn expo prebuild`. It finally succeeded a build on `npx eas build --profile development --platform android`.

**Comment by Montchy** [comment] 2023-08-14 08:22
Thank you for reporting this issue, but it is a duplicate of:

- https://github.com/margelo/react-native-quick-sqlite/issues/2

**Closed as completed by Montchy** 2023-08-14 08:22 UTC
Labels: duplicate
