### ISSUE TITLE
Expo 48 Android Build Error

### ISSUE THREAD

**Issue by elevyg** [margelo/react-native-nitro-sqlite#2] opened 2023-04-10 19:45 UTC
I'm facing the same issue presented here: https://github.com/ospfranco/react-native-quick-sqlite/issues/118

Any idea what can it be? I can help on fixing it but do not have much experience with this kind of configuraitons.

**Comment by eriklovdahl** [comment] 2023-04-28 21:29
Same problem. I'm guessing you are trying to build through EAS and since you don't have a root android config it will fail on:

`def USE_HERMES = rootProject.ext.hermesEnabled`

I used `patch-package` to just set it manually, but it would obviously be better to just fix the build script in the package. Someone with more experience with expo build steps and configuration can probably come up with a better solution :)

Would be great if this library would work out of the box with Expo EAS since expo-sqlite have messed up sqlite versions and problems with transactions.

**Comment by elevyg** [comment] 2023-05-03 15:15
I ended up doing the same!

**Comment by farmstrong8** [comment] 2023-05-24 12:34
i used this package to solve it https://www.npmjs.com/package/expo-gradle-ext-vars

**Comment by earonesty** [comment] 2023-06-17 05:31
in the root build gradle file:

```
ext {
  hermesEnabled = (findProperty('expo.jsEngine') ?: "hermes") == "hermes"
}
```

**Comment by Montchy** [comment] 2023-08-14 07:51
@elevyg thank you for creating the issue, can you please provide a reproduction example? :)

**Comment by ntuong196** [comment] 2024-07-03 03:07
I found the issue in [here](https://github.com/margelo/react-native-quick-sqlite/issues/42).
Beside update minSdkVersion, I also modify `app.json` to enable `hermes`

```json
  "expo": {
      ...
      "jsEngine": "hermes"
      ...
   }
```

But does anyone know why it doesn't work with `npx expo start`? 
Using eas build or `npx expo run:android` just take too long to restart the app.

**Comment by leogaletti** [comment] 2024-07-05 13:42
Try delete folder:

node_modules/react-native-quick-sqlite/android/.cxx/Debug

After delete folder, run android again.

npx react-native run-android

Its worked for me!

**Comment by chrispader** [comment] 2024-11-13 11:44
I'm going to close this issue, since this should have been fixed in one of the latest releases: https://github.com/margelo/react-native-quick-sqlite/releases/tag/v8.2.5

Lmk if this is still an issue. Our current supported minimum RN version is `v0.74.0` anyway, so i don't think this is relevant anymore.

**Closed as completed by chrispader** 2024-11-13 11:44 UTC
Labels: bug, triage:needs-reproduction
